
// This file was auto-generated by ML.NET Model Builder. 

using MLModel1_ConsoleApp1;

// Create single instance of sample data from first line of dataset for model input
MLModel1.ModelInput sampleData = new MLModel1.ModelInput()
{
    Longitude = -12222F,
    Latitude = 3786F,
    Housing_median_age = 210F,
    Total_rooms = 70990F,
    Total_bedrooms = 11060F,
    Population = 24010F,
    Households = 11380F,
    Median_income = 83014F,
    Ocean_proximity = @"NEAR BAY",
};

// Make a single prediction on the sample data and print results
var predictionResult = MLModel1.Predict(sampleData);

Console.WriteLine("Using model to make single prediction -- Comparing actual Median_house_value with predicted Median_house_value from sample data...\n\n");


Console.WriteLine($"Longitude: {-12222F}");
Console.WriteLine($"Latitude: {3786F}");
Console.WriteLine($"Housing_median_age: {210F}");
Console.WriteLine($"Total_rooms: {70990F}");
Console.WriteLine($"Total_bedrooms: {11060F}");
Console.WriteLine($"Population: {24010F}");
Console.WriteLine($"Households: {11380F}");
Console.WriteLine($"Median_income: {83014F}");
Console.WriteLine($"Median_house_value: {3585000F}");
Console.WriteLine($"Ocean_proximity: {@"NEAR BAY"}");


Console.WriteLine($"\n\nPredicted Median_house_value: {predictionResult.Score}\n\n");
Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

